<a href="https://colab.research.google.com/github/DTheArtist/pytorch/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tensors
*   A torch. Tensor is a Multi-demensional matrix containing elements of a single data type
*   Similar to Numpy Arrays, but full of fun things that make them work better on GPU's vs regular CPU's
* default datat ype of float32.
*More suitable for deep learning than a numpy array.
* Holds the data you need to do anything. Made for the power of using a GPU.




In [1]:
import torch
import numpy as np

# Lists

In [4]:
my_list = [1,2,3,4,5],[6,7,8,9,10]
my_list

([1, 2, 3, 4, 5], [6, 7, 8, 9, 10])

#Numpy Array

In [7]:
np1 = np.random.rand(3,4)
np1

array([[0.3443395 , 0.60369989, 0.61069783, 0.36199046],
       [0.29764844, 0.23676436, 0.68075763, 0.19536826],
       [0.44881217, 0.94869218, 0.48303521, 0.8887838 ]])

#Tensors

In [13]:
tensor_2d = torch.randn(3,4)
tensor_2d
#tensor_2d.dtype

tensor([[ 0.9106, -0.7111, -1.2760, -1.4182],
        [ 0.9911, -0.2477, -1.5711, -1.3748],
        [-0.4094,  0.2479,  1.7489, -2.2333]])

In [11]:
## Creat tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.3443, 0.6037, 0.6107, 0.3620],
        [0.2976, 0.2368, 0.6808, 0.1954],
        [0.4488, 0.9487, 0.4830, 0.8888]], dtype=torch.float64)

In [10]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

To Learn More or reference visit: https://pytorch.org/docs/main/tensors.html#